version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_APP_NAME=${APP_NAME}
      - VITE_APP_ENV=${APP_ENV}
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - jurisconnect-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongodb:27017/jurisconnect
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - ENVIRONMENT=${APP_ENV}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - RATE_LIMIT=${RATE_LIMIT}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jurisconnect-network

  mongodb:
    image: mongo:6.0
    container_name: jurisconnect-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jurisconnect
    networks:
      - jurisconnect-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  jurisconnect-network:
    driver: bridge

volumes:
  mongodb_data: 