apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- mongodb-deployment.yaml
- mongodb-service.yaml
- mongodb-pvc.yaml
- configmap.yaml
- secrets.yaml
- ingress.yaml

commonLabels:
  app: jurisconnect

configMapGenerator:
- name: jurisconnect-config
  literals:
  - NODE_ENV=production
  - MONGODB_URI=mongodb://mongodb:27017/jurisconnect
  - JWT_SECRET=your-jwt-secret
  - FRONTEND_URL=https://jurisconnect.com

secretGenerator:
- name: jurisconnect-secrets
  literals:
  - MONGODB_USERNAME=admin
  - MONGODB_PASSWORD=admin
  - JWT_SECRET=your-jwt-secret 